title: Una gran dosis de locura es necesaria
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.0561194175388664
color:
  saturation: 0.2076814693864435
  brandStrength: 0.8413194750901312
  lightness: 0.8093840042129159
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  rhythmicContrast: 0.5509830452501774
layout_spectrum: 0.8720034887082875
name: better psychosis
